
package com.xcelenergy.registration.wsdl.serviceplan;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtilityService", targetNamespace = "http://soap.ws.registration.utility.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtilityService {


    /**
     * 
     * @return
     *     returns java.util.List<com.xcelenergy.registration.wsdl.serviceplan.ServicePlan>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllServicePlans", targetNamespace = "http://soap.ws.registration.utility.com/", className = "com.xcelenergy.registration.wsdl.serviceplan.GetAllServicePlans")
    @ResponseWrapper(localName = "getAllServicePlansResponse", targetNamespace = "http://soap.ws.registration.utility.com/", className = "com.xcelenergy.registration.wsdl.serviceplan.GetAllServicePlansResponse")
    public List<ServicePlan> getAllServicePlans()
        throws Exception_Exception
    ;

}
