
package com.xcelenergy.registration.wsdl.serviceplan;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UtilityService", targetNamespace = "http://soap.ws.registration.utility.com/", wsdlLocation = "http://localhost:8080/XcelCustomerWS/Services/UtilityService?wsdl")
public class UtilityService_Service
    extends Service
{

    private final static URL UTILITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException UTILITYSERVICE_EXCEPTION;
    private final static QName UTILITYSERVICE_QNAME = new QName("http://soap.ws.registration.utility.com/", "UtilityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/XcelCustomerWS/Services/UtilityService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UTILITYSERVICE_WSDL_LOCATION = url;
        UTILITYSERVICE_EXCEPTION = e;
    }

    public UtilityService_Service() {
        super(__getWsdlLocation(), UTILITYSERVICE_QNAME);
    }

    public UtilityService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UTILITYSERVICE_QNAME, features);
    }

    public UtilityService_Service(URL wsdlLocation) {
        super(wsdlLocation, UTILITYSERVICE_QNAME);
    }

    public UtilityService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UTILITYSERVICE_QNAME, features);
    }

    public UtilityService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtilityService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UtilityService
     */
    @WebEndpoint(name = "UtilityServiceImplPort")
    public UtilityService getUtilityServiceImplPort() {
        return super.getPort(new QName("http://soap.ws.registration.utility.com/", "UtilityServiceImplPort"), UtilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtilityService
     */
    @WebEndpoint(name = "UtilityServiceImplPort")
    public UtilityService getUtilityServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.registration.utility.com/", "UtilityServiceImplPort"), UtilityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UTILITYSERVICE_EXCEPTION!= null) {
            throw UTILITYSERVICE_EXCEPTION;
        }
        return UTILITYSERVICE_WSDL_LOCATION;
    }

}
